//All error messages go here.

package main

const (
	ERRMSG_AUTHENTICATECONNECTION          = "authenticate connection"
	ERRMSG_DBEXISTS                        = "DB already exists"
	ERRMSG_DEVICECHECK                     = "check device/senders.txt for existing device by name"
	ERRMSG_DEVICEOFFLINE                   = "device offline"
	ERRMSG_DEVICENOTFOUND                  = "device not found in database"
	ERRMSG_DEVICEEXISTS                    = "device already exists"
	ERRMSG_BASEDIR_NOT_FOUND               = "could not find base working directory. device table potentially not initialized"
	ERRMSG_CHANNEL_OPERATION               = "channel operatoin"
	ERRMSG_CONSENT_TO_SEND                 = "consent-to-send error"
	ERRMSG_CREATE_DEVICE                   = "create device"
	ERRMSG_CREATE_DATAGRAM                 = "create datagram"
	ERRMSG_CREATE_DATAGRAM_STRUCT          = "create datagram struct"
	ERRMSG_CREATE_UUID                     = "create uuid"
	ERRMSG_DB_ATTEMPTED_INSERT_DUPLICATE   = "attempted to insert duplicate db entry"
	ERRMSG_DB_CONNECTION                   = "initiate MySQL database connection"
	ERRMSG_DB_PREPARE_STATEMENT            = "prepare statement"
	ERRMSG_DB_SELECT                       = "SELECT ... from DB"
	ERMMSG_DEVSLICE_NOTFOUND               = "Device slice not found from database"
	ERRMSG_DECODING                        = "Decoding Error"
	ERRMSG_DECODING_NIL_NODE               = "nil node (decoding)"
	ERRMSG_EMPTY_TRANSMISSION              = "empty transmission"
	ERRMSG_ENCODING                        = "Encoding Error"
	ERRMSG_ENCODING_HEADER_DECISION        = "Making heading decision (encoding)"
	ERRMSG_ENCODING_FREQTABLE_INVALID_ZERO = "Frequency Table Invalid/Zero (encoding)"
	ERRMSG_FETCH_IP_TABLE                  = "fetch ip table"
	ERRMSG_FETCH_IP_TABLE_NONE_SELECTED    = "ip address not selected for server"
	ERRMSG_ENCODING_TREE_DUPLICATE_INDICES = "duplicate huffman tree indics (encoding)"
	ERRMSG_FILEIO                          = "Create/Change File/Directory:\tdeviceauth.go"
	ERRMSG_FLUSH                           = "Flush syscall"
	ERRMSG_GETWD                           = "Get Current Working Directory:\tdeviceauth.go"
	ERRMSG_INITIALIZATION                  = "Error occurred while \"Initializing Everything\""
	ERRMSG_INVALID_ENUM                    = "Invalid enum"
	ERRMSG_IO                              = "IO operation"
	ERRMSG_INPUT_RETRIEVAL                 = "retrieving user input (on this machine)"
	ERRMSG_JSON_MARSHALL                   = "marshal JSON"
	ERRMSG_JSON_UNMARSHALL                 = "unmarshal JSON"
	ERRMSG_NETWORK_DATAGRAM                = "read Websocket datagram from connection"
	ERRMSG_NETWORK_DIAL                    = "dial network connection"
	ERRMSG_NETWORK_CONNECTION              = "new network connection"
	ERRMSG_NETWORK_CONNECTION_CLIENT       = "new client connection"
	ERRMSG_NETWORK_INVALID_PORT            = "result of invalid port (successful = valid, uncuccessful = invalid)"
	ERRMSG_NETWORK_PARSE_HTTPREQ           = "parse http request"
	ERRMSG_NETWORK_PORTS_OCCUPIED          = "all ports are occupied"
	ERRMSG_NETWORK_SEND_LEN0               = "attempted send of length 0"
	ERRMSG_NETWORK_SEND_TOOSHORT           = "attempted to send message too short for function"
	ERRMSG_NETWORK_READ                    = "network connection read"
	ERRMSG_NETWORK_RECEIVE_STRUCT          = "network receive struct"
	ERRMSG_NETWORK_SEND_STRUCT             = "network send struct"
	ERRMSG_NETWORK_WRITE                   = "network connection write"
	ERRMSG_NILPTR                          = "nil pointer"
	ERRMSG_READCONN                        = "read connection"
	ERRMSG_READ                            = "read"
	ERRMSG_REGISTER_DEVICE                 = "Register device"
	ERRMSG_SEEK                            = "seek"
	ERRMSG_SELFSEND                        = "check for self-send"
	ERRMSG_SERVER_START                    = "start server"
	ERRMSG_TCPLISTENER                     = "create TCPListener"
	ERRMSG_TIME_INVALID                    = "invalid time"
	ERRMSG_TIMEOUT                         = "value timed out"
	ERRMSG_WRITE                           = "write"
	ERRMSG_ZEROLENGTH                      = "message with zero length"
)
